#!/usr/bin/env bash
# Bash script displays "To infinity and beyond" but prints "I am invincible!!!" for SIGTERM signal
trap "echo I am invincible!!!" SIGTERM
while true
do
echo "To infinity and beyond"
sleep 2
done
