#!/usr/bin/env bash
# Clock counts like a conventional clock
h=0
n=1
while [ $h -le 12 ]
do
    case $n in
	1)
	    echo "Hour:" $h
	    echo $n
	    ;;
	60)
	    n=0
	    ((h++))
	    ;;
	*)
	    echo $n
    esac
    ((n++))
done
