#!/usr/bin/env bash
# Clock counts like a conventional clock
h=0
m=1
while [ $h -le 12 ]
do
    case $m in
	1)
	    echo "Hour:" $h
	    echo $m
	    ;;
	60)
	    m=0
	    ((h++))
	    ;;
	*)
	    echo $m
    esac
    ((m++))
done
